In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
print(pd.__version__)

3.0.2

In [4]:
print(np.__version__)

2.4.4

In [5]:
df = pd.read_csv("Saas_Churn_Raw_Dataset.csv")

In [6]:
df.head()

   customer_id signup_date  ... tenure_months             churn_reason
0  CUST-000001  2024-01-01  ...             0  Poor Support Experience
1  CUST-000002  2024-01-01  ...             0        Low Product Usage
2  CUST-000003  2024-01-01  ...             5        Low Product Usage
3  CUST-000004  2024-01-01  ...            23                      NaN
4  CUST-000005  2024-01-01  ...            23                      NaN

[5 rows x 24 columns]

In [7]:
print(df.shape)

(44440, 24)

In [8]:
print(df.dtypes)

customer_id                  str
signup_date                  str
plan_type                    str
industry                     str
company_size                 str
country                      str
acquisition_channel          str
billing_cycle                str
seats_purchased            int64
seats_active               int64
mrr                      float64
onboarding_completed         str
avg_monthly_logins       float64
features_used_count        int64
days_since_last_login      int64
support_tickets_90d        int64
avg_resolution_hours     float64
csat_score               float64
failed_payments_6m         int64
payment_method               str
customer_status              str
churn_date                   str
tenure_months              int64
churn_reason                 str
dtype: object

In [9]:
print(df.isna().sum())

customer_id                  0
signup_date                  0
plan_type                    0
industry                   713
company_size                 0
country                      0
acquisition_channel        668
billing_cycle                0
seats_purchased              0
seats_active                 0
mrr                          0
onboarding_completed         0
avg_monthly_logins           0
features_used_count          0
days_since_last_login        0
support_tickets_90d          0
avg_resolution_hours     13566
csat_score                1596
failed_payments_6m           0
payment_method               0
customer_status              0
churn_date               37714
tenure_months                0
churn_reason             37764
dtype: int64

In [10]:
print(df.duplicated().sum())

440

In [11]:
df = df.drop_duplicates()

In [12]:
print(df.shape)

(44000, 24)

In [13]:
df.columns = df.columns.str.title()

In [14]:
df.head()

   Customer_Id Signup_Date  ... Tenure_Months             Churn_Reason
0  CUST-000001  2024-01-01  ...             0  Poor Support Experience
1  CUST-000002  2024-01-01  ...             0        Low Product Usage
2  CUST-000003  2024-01-01  ...             5        Low Product Usage
3  CUST-000004  2024-01-01  ...            23                      NaN
4  CUST-000005  2024-01-01  ...            23                      NaN

[5 rows x 24 columns]

In [15]:
df["Plan_Type"].unique()

<StringArray>
[      'Basic',         'Pro',  'Enterprise',       'basic',      ' Basic',
  'enterprise',         'PRO',         'pro',  'ENTERPRISE', 'Enterprise ',
       'BASIC',       ' Pro ',        'Pro ']
Length: 13, dtype: str

In [16]:
df["Country"].unique()

<StringArray>
[     'India',  'Australia',    'Germany',        'USA',         'UK',
 'Australia ',  'Singapore',        'UAE',        'usa',        'U.K',
       'USA ',      'INDIA',         'uk',        'UK ',  'australia',
    'germany',    'GERMANY',       ' UAE',       'UAE ',        'uae',
      'india',      'U.S.A',  'singapore',     ' India', ' Singapore',
   'Germany ',  'AUSTRALIA',  'SINGAPORE']
Length: 28, dtype: str

In [17]:
df["Payment_Method"].unique()

<StringArray>
[  'Credit Card',           'UPI',        'PayPal', 'Bank Transfer',
        'PAYPAL', 'bank transfer',   'credit card',    'Debit Card',
          ' UPI',  ' Credit Card',   'Credit_Card',           'Upi',
        'paypal',           'upi',    'Debit_Card', 'BANK TRANSFER',
   'CREDIT CARD',        'Paypal',    'DEBIT CARD', 'Bank_Transfer',
    'debit card']
Length: 21, dtype: str

In [18]:
df["Payment_Method"] = df["Payment_Method"].str.replace("_", " ")

In [19]:
cols_to_convert = ["Plan_Type", "Country", "Payment_Method"]
for col in cols_to_convert:
    df[col] = df[col].str.strip().str.title()

In [20]:
df["Country"].unique()

<StringArray>
[    'India', 'Australia',   'Germany',       'Usa',        'Uk', 'Singapore',
       'Uae',       'U.K',     'U.S.A']
Length: 9, dtype: str

In [21]:
df["Country"] = df["Country"].replace({"Usa": "USA", "U.S.A": "USA", "Uk": "UK", "U.K": "UK", "Uae": "UAE"})

In [22]:
df["Payment_Method"] = df["Payment_Method"].replace({"Upi": "UPI"})

In [23]:
df["Plan_Type"].unique()

<StringArray>
['Basic', 'Pro', 'Enterprise']
Length: 3, dtype: str

In [24]:
df["Country"].unique()

<StringArray>
['India', 'Australia', 'Germany', 'USA', 'UK', 'Singapore', 'UAE']
Length: 7, dtype: str

In [25]:
df["Payment_Method"].unique()

<StringArray>
['Credit Card', 'UPI', 'Paypal', 'Bank Transfer', 'Debit Card']
Length: 5, dtype: str

In [26]:
print(df.isna().sum())

Customer_Id                  0
Signup_Date                  0
Plan_Type                    0
Industry                   704
Company_Size                 0
Country                      0
Acquisition_Channel        661
Billing_Cycle                0
Seats_Purchased              0
Seats_Active                 0
Mrr                          0
Onboarding_Completed         0
Avg_Monthly_Logins           0
Features_Used_Count          0
Days_Since_Last_Login        0
Support_Tickets_90D          0
Avg_Resolution_Hours     13413
Csat_Score                1586
Failed_Payments_6M           0
Payment_Method               0
Customer_Status              0
Churn_Date               37353
Tenure_Months                0
Churn_Reason             37403
dtype: int64

In [27]:
df["Industry"] = df["Industry"].fillna("Unknown")

In [28]:
df["Acquisition_Channel"] = df["Acquisition_Channel"].fillna("Unknown")

In [29]:
df["Churn_Reason"].unique()

<StringArray>
['Poor Support Experience',       'Low Product Usage',
                       nan,  'Switched to Competitor',
         'Business Closed',        'Pricing Too High',
        'Missing Features',         'Payment Failure',
                 'Unknown']
Length: 9, dtype: str

In [30]:
churned_missing = (df["Customer_Status"] == "Churned") & (df["Churn_Reason"].isna())
df.loc[churned_missing, "Churn_Reason"] = "Not Recorded"

In [31]:
df["Churn_Reason"] = df["Churn_Reason"].replace("Unknown", "Not Recorded")

In [32]:
df["Churn_Reason"] = df["Churn_Reason"].fillna("Unknown")

In [33]:
df["Churn_Reason"].value_counts()

Churn_Reason
Unknown                    37353
Low Product Usage           2150
Pricing Too High            1512
Switched to Competitor       883
Missing Features             779
Poor Support Experience      757
Business Closed              236
Payment Failure              230
Not Recorded                 100
Name: count, dtype: int64

In [34]:
missing_hours = (df["Avg_Resolution_Hours"].isna()) & (df["Support_Tickets_90D"] > 0)
df.loc[missing_hours, "Avg_Resolution_Hours"] = 0

In [35]:
print(df.isna().sum())

Customer_Id                  0
Signup_Date                  0
Plan_Type                    0
Industry                     0
Company_Size                 0
Country                      0
Acquisition_Channel          0
Billing_Cycle                0
Seats_Purchased              0
Seats_Active                 0
Mrr                          0
Onboarding_Completed         0
Avg_Monthly_Logins           0
Features_Used_Count          0
Days_Since_Last_Login        0
Support_Tickets_90D          0
Avg_Resolution_Hours     12808
Csat_Score                1586
Failed_Payments_6M           0
Payment_Method               0
Customer_Status              0
Churn_Date               37353
Tenure_Months                0
Churn_Reason                 0
dtype: int64

In [36]:
df["Signup_Date"] = pd.to_datetime(
    df["Signup_Date"], format="mixed", errors="coerce"
)

In [37]:
df["Churn_Date"] = pd.to_datetime(
    df["Churn_Date"], format="mixed", errors="coerce"
)

In [38]:
print(df.dtypes)

Customer_Id                         str
Signup_Date              datetime64[us]
Plan_Type                           str
Industry                            str
Company_Size                        str
Country                             str
Acquisition_Channel                 str
Billing_Cycle                       str
Seats_Purchased                   int64
Seats_Active                      int64
Mrr                             float64
Onboarding_Completed                str
Avg_Monthly_Logins              float64
Features_Used_Count               int64
Days_Since_Last_Login             int64
Support_Tickets_90D               int64
Avg_Resolution_Hours            float64
Csat_Score                      float64
Failed_Payments_6M                int64
Payment_Method                      str
Customer_Status                     str
Churn_Date               datetime64[us]
Tenure_Months                     int64
Churn_Reason                        str
dtype: object

In [39]:
invalid_dates_df = df[df["Churn_Date"] < df["Signup_Date"]]
print(len(invalid_dates_df))

88

In [40]:
df = df.drop(invalid_dates_df.index)

In [41]:
print(df.shape)

(43912, 24)

In [42]:
end_date = df["Churn_Date"].fillna(pd.Timestamp("2025-11-30"))

In [43]:
df["Tenure_Months"] = (end_date.dt.year - df["Signup_Date"].dt.year) * 12 + (
    end_date.dt.month - df["Signup_Date"].dt.month
)

In [44]:
df.loc[df["Tenure_Months"] < 0, "Tenure_Months"] = 0

In [45]:
df["Signup_Date"] = df["Signup_Date"].dt.date

In [46]:
df["Churn_Date"] = df["Churn_Date"].dt.date

In [47]:
df.head()

   Customer_Id Signup_Date  ... Tenure_Months             Churn_Reason
0  CUST-000001  2024-01-01  ...             0  Poor Support Experience
1  CUST-000002  2024-01-01  ...             0        Low Product Usage
2  CUST-000003  2024-01-01  ...             5        Low Product Usage
3  CUST-000004  2024-01-01  ...            22                  Unknown
4  CUST-000005  2024-01-01  ...            22                  Unknown

[5 rows x 24 columns]

In [48]:
print(df.dtypes)

Customer_Id                  str
Signup_Date               object
Plan_Type                    str
Industry                     str
Company_Size                 str
Country                      str
Acquisition_Channel          str
Billing_Cycle                str
Seats_Purchased            int64
Seats_Active               int64
Mrr                      float64
Onboarding_Completed         str
Avg_Monthly_Logins       float64
Features_Used_Count        int64
Days_Since_Last_Login      int64
Support_Tickets_90D        int64
Avg_Resolution_Hours     float64
Csat_Score               float64
Failed_Payments_6M         int64
Payment_Method               str
Customer_Status              str
Churn_Date                object
Tenure_Months              int32
Churn_Reason                 str
dtype: object

In [49]:
print(df.isna().sum())

Customer_Id                  0
Signup_Date                  0
Plan_Type                    0
Industry                     0
Company_Size                 0
Country                      0
Acquisition_Channel          0
Billing_Cycle                0
Seats_Purchased              0
Seats_Active                 0
Mrr                          0
Onboarding_Completed         0
Avg_Monthly_Logins           0
Features_Used_Count          0
Days_Since_Last_Login        0
Support_Tickets_90D          0
Avg_Resolution_Hours     12783
Csat_Score                1584
Failed_Payments_6M           0
Payment_Method               0
Customer_Status              0
Churn_Date               37353
Tenure_Months                0
Churn_Reason                 0
dtype: int64

In [50]:
print(df.duplicated().sum())

0

In [51]:
print(df["Customer_Id"].duplicated().sum())

0

In [52]:
print(df.shape)

(43912, 24)

In [53]:
df.to_csv("Saas_Churn_Cleaned_Data.csv", index=False)